import crc32 from 'crc32';

let words=['aggregator','agile','ajax','algorithm','benchmark','backend','beta','bigdata','bleedingedge','blogosphere','clickthrough','cloud','cloudops','cloudscale','collaboration','analytics','cms','convergence','crossplatform','synergy','leftpad','datafication','datamining','datascience','datavis','deepdive','deepweb','designpattern','devops','digitaldivide','xml','drm','digitalsignage','disruptivetech','jsx','dotbomb','npm','elearning','end2end','engine','refactor','enterprise','servicebus','evolution','framework','css','fuzzylogic','growthhacking','html','immersion','infohighway','internetofthings','innovation','mashup','microservices','mobile','module','service','nanotech','netiquette','nfv','nextgen','objectoriented','functional','omnichannel','bitcoin','parser','paas','podcasting','portal','realtime','responsive','dotio','saas','scalability','skeuomorphic','social','transpile','minify','spam','struts','syncup','lifecycle','tagging','seo','thoughtleader','sprint','ui','ux','github','viral','virtualize','vlogging','vortal','malware','webinar','weblog','webservices','wikiality','workflow','webscale','es6','babel','gulp','recursion','emscripten','webassembly','eslint','webpack','dojotoolkit','jquery','midori','polyfill','hax','react','yui','anychart','d3','highcharts','easeljs','infovistoolkit','p5','pixi','plotly','processing','raphaël','swf','webgl','velocity','whitestormjs','extjs','angularjs','bootstrap','dhtml','dojowidgets','foundation','polymer','jqueryui','jqwidgets','igniteui','kendoui','api','wijmo5','openui5','qooxdoo','smartclient','webix','winjs','vue','amplesdk','glow','livelykernel','script.aculo.us','typescript','googleclosure','joose','jsphp','mochikit','pdf','rico','socket.io','spryframework','underscore','cascade','handlebars','jquerymobile','mustache','jasmine','mocha','qunit','unit','databind','backbone','cappuccino','chaplin','echo','ember','enyo','webkit','mvc','knockout','meteor','mojito','mootools','nodejs','prototype','cycle','rialtotoolkit','sproutcore','wakanda','abstract','arguments','boolean','break','byte','case','catch','char','class','const','continue','debugger','default','delete','do','double','else','enum','eval','export','extends','false','final','finally','float','for','function','goto','if','implements','import','in','instanceof','int','interface','let','long','native','new','null','package','private','protected','public','return','short','static','super','switch','synchronized','this','throw','throws','transient','true','try','typeof','var','void','volatile','while','with','yield','mozilla','google'];

export function getHash(value) {

    let hexHash = crc32(value);

    return hexHash
        .match(/../g)
        .map(hex => words[parseInt(hex, 16)])
        .join('-');
}